### ISSUE TITLE
python main.py errors.

### ISSUE THREAD

**Issue by jiapei100** [fomorians/distracted-drivers-tf#3]
jiapei@jiapei-GT72-6QE:~/Downloads/kaggle/StateFarmDistractedDriverDetection/distracted-drivers-tf$ python main.py 
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
Loading dataset dataset/data_20.pkl...
('Running fold...', 18001, 4423)
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 980M
major: 5 minor: 2 memoryClockRate (GHz) 1.1265
pciBusID 0000:01:00.0
Total memory: 3.99GiB
Free memory: 3.64GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980M, pci bus id: 0000:01:00.0)
WARNING:tensorflow:Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`.
Attempting to restore None...
Could not find checkpoint to restore.
Begin training...
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    model.train(X_train, y_train, epoch)
  File "/home/jiapei/Downloads/kaggle/StateFarmDistractedDriverDetection/distracted-drivers-tf/model.py", line 110, in train
    self.is_training: True
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 553, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (50, 3, 32, 24) for Tensor 'Placeholder_1:0', which has shape '(?, 24, 32, 3)'

**Comment by jiapei100** [comment]
Looks like this morning's update:

> Loading dataset dataset/data_20.pkl...
> Running fold... 18001 4423
> I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
> name: GeForce GTX 980M
> major: 5 minor: 2 memoryClockRate (GHz) 1.1265
> pciBusID 0000:01:00.0
> Total memory: 3.99GiB
> Free memory: 3.63GiB
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980M, pci bus id: 0000:01:00.0)
> Traceback (most recent call last):
>   File "main.py", line 47, in <module>
>     model = Model(layers, num_folds, batch_size=BATCH_SIZE)
>   File "/home/jiapei/Downloads/kaggle/StateFarmDistractedDriverDetection/distracted-drivers-tf/model.py", line 32, in **init**
>     self.global_step = tf.Variable(0, trainable=False, name='global_step')
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 210, in **init**
>     dtype=dtype)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 250, in _init_from_args
>     init_from_fn = isinstance(initial_value, collections.Callable)
> AttributeError: 'NoneType' object has no attribute 'Callable'

Cheers
Pei
