### ISSUE TITLE
cannot import name 'control_flow_ops'

### ISSUE THREAD

**Issue by TanLingxiao** [fomorians/distracted-drivers-tf#4]
I use tensorflow1.0 in Ubuntu14,python 3.4

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from model import Model
  File "F:\distracted-drivers-tf-master\model.py", line 6, in <module>
    from layers import Input
  File "F:\distracted-drivers-tf-master\layers.py", line 4, in <module>
    from tensorflow.python import control_flow_ops
ImportError: cannot import name 'control_flow_ops'

**Comment by TanLingxiao** [comment]
I solved it by changing to 'from tensorflow.python.ops import control_flow_ops' in  line 4 of layers.py.
